"""add user_id to applications

Revision ID: ebba69b2b9a8
Revises: 
Create Date: 2026-09-22 22:16:45.098503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebba69b2b9a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "applications",
        sa.Column("user_id", sa.Integer(), nullable=True),
    )

    # Assign existing applications to the first user.
    op.execute("""
        UPDATE applications
        SET user_id = (SELECT id FROM users ORDER BY id LIMIT 1)
        WHERE user_id IS NULL
    """)

    op.alter_column("applications", "user_id", nullable=False)

    op.create_foreign_key(
        "fk_applications_user_id_users",
        "applications",
        "users",
        ["user_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'user_id')
    # ### end Alembic commands ###
